// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCbmSIRwfMLDAwLRv3iqkyy7ACiY77mkSk",
      authDomain: "travel-612a2.firebaseapp.com",
      databaseURL:
          "https://travel-612a2-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "travel-612a2",
      storageBucket: "travel-612a2.appspot.com",
      messagingSenderId: "264196876413",
      appId: "1:264196876413:web:41a55d359bf5d10b77e914");

  static const FirebaseOptions android = FirebaseOptions(
    authDomain: "travel-612a2.firebaseapp.com",
    apiKey: 'AIzaSyCsXR8FuUH5cJDkdh60b3LcisMGjHzmw6o',
    appId: '1:264196876413:android:ac04deed3f880ba877e914',
    messagingSenderId: '264196876413',
    projectId: 'travel-612a2',
    databaseURL:
        'https://travel-612a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travel-612a2.appspot.com',
  );
}
